name: CI


on:
   push:
     branches: [main]
   pull_request:
     branch: [main]

jobs:
  lint:
    runs-on: linux-latest
    name: Run eslint
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-no
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run lint